<a href="https://colab.research.google.com/github/keidenmw21-prog/MIS433/blob/main/Python_Basics_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Assignment: Python Basics
We assume you are using Python 3 in this course.

## Question 1

You've learned different data types in Python. Now, let's test your knowledge.

You need to use to format strings.

Write a program using the "f-strings" (https://realpython.com/python-f-strings/) and user input function to convert temperatures from Fahrenheit to Celsius. [Formula: Celsius = (Fahrenheit – 32)*5/9]

Hint: you may need int() or float() function

An example program output:
```
Please enter the temperature in Fahrenheit: 140
140F is 60.0 in Celsius.
```

In [ ]:
# an example of f-strings and user input function
username = input('What\'s your name? ')
print(f'Welcome, {username}!')

What's your name? Keiden
Welcome, Keiden!


In [ ]:
# complete your program here
f = input('Please enter the temperature in Fahrenheit: ')
f = float(f)
print(f)

#Celsius = (Fahrenheit – 32)*5/9
c = (f - 32) * 5/9

print(f'{f}F is {c} in Celsius. ')
#print(str(f)+'F is '+str(c)+' in Celsius. ')

Please enter the temperature in Fahrenheit: 50
50.0
50.0F is 10.0 in Celsius. 


Now, do the oppsoite by convert temperatures from Celsius to Fahrenheit.
Another example:
```
Please enter the temperature in Celcius: 60
60C is 140.0 in Fahrenheit.
```

In [ ]:
# complete your program here
c = float(input('Please enter the temperature in Celcius: '))
print (c)
f = c*(9/5) + 32
print(f'{c}C is {f} in Fahrenheit. ')

Please enter the temperature in Celcius: 30
30.0
30.0C is 86.0 in Fahrenheit. 


Next, let's make it a bit challenging by adding conditional statements to convert temperatures to and from Celsius, Fahrenheit. [Formula: Celsius/5 = (Fahrenheit – 32)/9]

An example program output:
```
Please enter the temperature: 60
Is this in Celsius or Fahrenheit? C
60C is 140 in Fahrenheit
```

Another example:
```
Please enter the temperature: 140
Is this Celsius or Fahrenheit? F
140F is 60 in Celsius
```

In [ ]:
# complete your program here
d = input('Please enter the temperature: ')
m = input('Is this in Celsius or Fahrenheit? ')

if m == 'C':
  f = c*(9/5) + 32
  print(f'{c}C is {f} in Fahrenheit. ')
if m == "F":
  c = (f - 32) * 5/9
  print(f'{f}C is {c} in Celcius. ')


Please enter the temperature: 20
Is this in Celsius or Fahrenheit? C
30.0C is 86.0 in Fahrenheit. 


## Question 2

Have some fun with strings.

In [ ]:
sentence = "Talk is cheap. Show me the code - Linus Torvalds"

In [ ]:
# Find the length of this sentence.
len(sentence)

48

In [ ]:
# Convert the whole string to lower case.
sentence.lower()

'talk is cheap. show me the code - linus torvalds'

In [ ]:
# Extract a substring from the 10th character from left to the 10th character from right.
print(sentence[10:-10])

eap. Show me the code - Linu


In [ ]:
# Split the sentence into a list of substrings by space ' '.
print(sentence.split())

['Talk', 'is', 'cheap.', 'Show', 'me', 'the', 'code', '-', 'Linus', 'Torvalds']


In [ ]:
# Given the sentence, output a list of words in lowercase (without punctuations).
print(sentence.lower().split())

['talk', 'is', 'cheap.', 'show', 'me', 'the', 'code', '-', 'linus', 'torvalds']


In [ ]:
# Count the total number of vowels in the sentence.
vowels = ['a','e','i','o','u']
vowels = 'aeiou'
count = 0
for v in vowels:
    print(v, sentence.lower().count(v))
    count += sentence.lower().count(v)
print(f"The total number of vowels is {count}.")

a 3
e 4
i 2
o 3
u 1
The total number of vowels is 13.


In [ ]:
# Find the positions (indexes) of all vowels in the sentence.
vowels = 'aeiou'
vowel_positions = []
for i in range(len(sentence)):
    if sentence[i].lower() in vowels:
        vowel_positions.append(i)
print(vowel_positions)

[1, 5, 10, 11, 17, 21, 25, 28, 30, 35, 37, 41, 44]


## Question 3

Review list comprehension if needed: https://realpython.com/list-comprehension-python/

The formula for list comprehension is: `new_list = [expression for member in iterable (if conditional)]`

You need to do the following:

In [ ]:
# Use a loop to create a list of 5 cube numbers and print the list：[0, 1, 8, 27, 64]
cubes = []
for number in range(5):
    cubes.append(number*number*number)
cubes

[0, 1, 8, 27, 64]

In [ ]:
# Use list comprehension to create the same list
cubes = [number**3 for number in range(5)]
cubes

[0, 1, 8, 27, 64]

In [ ]:
# Find the postions (indexes) of all vowels in a sentence using list comprehension
sentence = "Toto, I\'ve a feeling we\'re not in Kansas anymore. - THE WIZARD OF OZ (1939)"

vowel_index = [i for i, char in enumerate(sentence) if char.lower() in 'aeiou']

print(vowel_index)


[1, 3, 6, 9, 11, 14, 15, 17, 22, 25, 28, 31, 35, 38, 41, 45, 47, 54, 57, 59, 63, 66]


In [ ]:
# Use a loop to create a list of first n numbers in the Fibonacci sequence
# [0, 1, 1, 2, 3, 5, 8, ...]
fibonacci = []
n = input('How many numbers do you want? ')
n = int(n)

# add your code here
if n == 1:
  fibonacci = [0]
elif n == 2:
  fibonacci = [0,1]
elif n > 2:
  fibonacci = [0,1]
  while len(fibonacci) < n:
    fibonacci.append(fibonacci[-1] + fibonacci[-2])

print(fibonacci)

How many numbers do you want? 5
[0, 1, 1, 2, 3]


## Question 4

This question is about Python dictionary.

|Vaccine|Efficacy|
|-----|-------|
|Pfizer|95%|
|Moderna|95%|
|AstraZeneca|72%|
|Johnson & Johnson|66%|

Source: https://www.biospace.com/article/comparing-covid-19-vaccines-pfizer-biontech-moderna-astrazeneca-oxford-j-and-j-russia-s-sputnik-v/

In [ ]:
# Create a dictionary to save the data of vaccines and their efficacy. (save 95% as 0.95)
v_dict = {'Pfizer':0.95, 'Moderna':0.95, "AstraZeneca":0.72, "Johnson & Johnson": 0.66}
print(v_dict)

{'Pfizer': 0.95, 'Moderna': 0.95, 'AstraZeneca': 0.72, 'Johnson & Johnson': 0.66}


In [ ]:
v = input('Which vaccine? ')
# print the efficacy of the vaccine
print(v_dict[v])

Which vaccine? Pfizer
0.95


In [ ]:
# add another vaccine 'Sputnik V' with 91.4% efficacy rate to the dictionary
v_dict["Sputnik V"] = 0.916
print(v_dict)

{'Pfizer': 0.95, 'Moderna': 0.95, 'AstraZeneca': 0.72, 'Johnson & Johnson': 0.66, 'Sputnik V': 0.916}


In [ ]:
# add another vaccine 'Sinovac' with 50.38% efficacy rate to the dictionary
v_dict["Sinovac"] = 0.5038
print(v_dict)

{'Pfizer': 0.95, 'Moderna': 0.95, 'AstraZeneca': 0.72, 'Johnson & Johnson': 0.66, 'Sputnik V': 0.916, 'Sinovac': 0.5038}


In [ ]:
# Print vaccines with efficacy lower than 90%.
for vaccine,efficacy in v_dict.items():
  if efficacy<0.9:
    print(f"{vaccine}: {efficacy}")

AstraZeneca: 0.72
Johnson & Johnson: 0.66
Sinovac: 0.5038


In [ ]:
# delete the Sinovac vaccine from the dictionary.
del v_dict["Sinovac"]
print(v_dict)

{'Pfizer': 0.95, 'Moderna': 0.95, 'AstraZeneca': 0.72, 'Johnson & Johnson': 0.66, 'Sputnik V': 0.916}


In [ ]:
#Count the occurrence of each alphabet (no space ' ') in this sentence.
sentence = 'the quick brown fox jumps over the lazy dog'

# Save the result in a dictionary
ch_dict = {}

# Use a loop to iterate all characters
# add your code here
for ch in sentence:
  if ch!= ' ':
    if ch in ch_dict:
      ch_dict[ch] += 1
    else:
      ch_dict[ch] = 1

# print the dictionary
print(ch_dict)

{'t': 2, 'h': 2, 'e': 3, 'q': 1, 'u': 2, 'i': 1, 'c': 1, 'k': 1, 'b': 1, 'r': 2, 'o': 4, 'w': 1, 'n': 1, 'f': 1, 'x': 1, 'j': 1, 'm': 1, 'p': 1, 's': 1, 'v': 1, 'l': 1, 'a': 1, 'z': 1, 'y': 1, 'd': 1, 'g': 1}


## Question 5

Next, we will practice with Numpy arrays.  

In [ ]:
import numpy as np

In [ ]:
# create a 1-D array of first 20 positive even numbers (starting with 2)
np.arange(2,42,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40])

In [ ]:
# create a 1-D array of first 20 positive odd numbers (starting with 1)
np.arange(1,40,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39])

In [ ]:
# create a 10x10 array in the following format:
# first row: [0,1,...,9]
# second row: [10,11,...,19]
# ...
# tenth row: [90,91,...,99]
np.arange(100).reshape(10,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [ ]:
# Create a 10x10 array of normally distributed random values
# with mean 0 and standard deviation 1
M = np.random.normal(0,1,(10,10))
M
#M.shape

array([[ 1.85450748, -1.18668667, -0.81262604, -1.49316173, -1.05451805,
         0.34950399, -0.8412532 , -0.07615078,  0.20058212,  0.46778759],
       [-1.07458356, -0.69202448, -0.47542704, -0.85435039, -2.30124356,
         0.00492212,  0.06517951, -1.83269208, -0.72228965, -1.52121643],
       [ 1.04964866, -0.30356591, -0.42515353, -1.07069964,  1.23983374,
        -1.29156577,  0.51845207,  1.54371412,  1.12019845,  1.1031066 ],
       [ 0.24125366,  0.59638949,  0.81459226, -0.95399525, -1.48240377,
        -0.11718693,  0.56413994, -1.44189618,  0.2429676 ,  1.11067723],
       [ 1.58956423, -1.9378409 ,  1.57950591, -1.48568239,  1.32805937,
         1.23479597,  0.13405542,  0.44142302, -0.48613483,  0.17743268],
       [-0.20095673,  0.11784333,  1.25967714, -1.13837558,  0.52326369,
        -0.62247832,  0.19285016, -0.24733721,  0.74404541,  1.76094707],
       [ 1.59878726,  0.62027175,  0.24960878, -0.58777214, -0.44644008,
        -0.07812794, -0.94331203, -0.63505064

In [ ]:
# Count the numbers in M with an absolute value greater than 1.
count = np.sum(np.abs(M) > 1)
print(f"{count}")

35


In [ ]:
# Reference: https://numpy.org/doc/stable/reference/random/generated/numpy.random.randint.html

# Input the number of rows (input an integer >= 3)
r = input('Row count: ')
r = int(r)

# Input the number of rows (input another integer >= 3)
c = input('Column count: ')
c = int(c)

# Hint: you may want to use the function int().

# Create a r x c array of random integers between 10 (inclusive) and 20 (exclusive).
arr = np.random.randint(10,20,(r,c))
arr

Row count: 5
Column count: 6


array([[11, 16, 13, 17, 19, 13],
       [16, 13, 16, 10, 11, 12],
       [16, 13, 19, 13, 17, 16],
       [16, 18, 10, 14, 16, 12],
       [14, 19, 10, 10, 14, 14]])

In [ ]:
# output the element in the first row and the third column
int(arr[0,2])

13

In [ ]:
# output the element in the second row and the last column
int(arr[1,-1])

12

In [ ]:
# output the second row of the array
arr[1,:]

array([16, 13, 16, 10, 11, 12])

In [ ]:
# output the second last row of the array
arr[-2,:]

array([16, 18, 10, 14, 16, 12])

In [ ]:
# output the second column of the array
arr[:,2]

array([13, 16, 19, 10, 10])

In [ ]:
# output the second last column of the array
arr[:,-2]

array([19, 11, 17, 16, 14])

In [ ]:
# output the upper-left 3x3 sub-array
arr[:3,:3]

array([[11, 16, 13],
       [16, 13, 16],
       [16, 13, 19]])

In [ ]:
# output the bottom-left 3x3 sub-array
arr[-3:,:3]

array([[16, 13, 19],
       [16, 18, 10],
       [14, 19, 10]])

In [ ]:
# output the upper-right 3x3 sub-array
arr[:3,-3:]

array([[17, 19, 13],
       [10, 11, 12],
       [13, 17, 16]])

In [ ]:
# output the bottom-right 3x3 sub-array
arr[-3:,-3:]

array([[13, 17, 16],
       [14, 16, 12],
       [10, 14, 14]])

In [ ]:
# Create a 1-D array from 1 to 50 (inclusive)
A = np.arange(1,51,1)
# Reshape A to a 5x10 array in the following format:
# first row: [1,...,10]
# second row: [11,...,20]
# ...
# fifth row: [41,...,50]

A = A.reshape(5,10)
A

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

In [ ]:
# add a row [51,...,60] to A
newrow = np.arange(51,61)
A=np.vstack([A,newrow])
A

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50],
       [51, 52, 53, 54, 55, 56, 57, 58, 59, 60]])

In [ ]:
# split the new A (6x10) to two 3x10 arrays A1 and A2
A1, A2 = np.vsplit(A,2)

In [ ]:
# Add 10 to each element of A
A = A+10
A

array([[11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50],
       [51, 52, 53, 54, 55, 56, 57, 58, 59, 60],
       [61, 62, 63, 64, 65, 66, 67, 68, 69, 70]])

In [ ]:
# Calculate the square root of each element in A
A = np.sqrt(A)
A

array([[3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
        4.        , 4.12310563, 4.24264069, 4.35889894, 4.47213595],
       [4.58257569, 4.69041576, 4.79583152, 4.89897949, 5.        ,
        5.09901951, 5.19615242, 5.29150262, 5.38516481, 5.47722558],
       [5.56776436, 5.65685425, 5.74456265, 5.83095189, 5.91607978,
        6.        , 6.08276253, 6.164414  , 6.244998  , 6.32455532],
       [6.40312424, 6.4807407 , 6.55743852, 6.63324958, 6.70820393,
        6.78232998, 6.8556546 , 6.92820323, 7.        , 7.07106781],
       [7.14142843, 7.21110255, 7.28010989, 7.34846923, 7.41619849,
        7.48331477, 7.54983444, 7.61577311, 7.68114575, 7.74596669],
       [7.81024968, 7.87400787, 7.93725393, 8.        , 8.06225775,
        8.1240384 , 8.18535277, 8.24621125, 8.30662386, 8.36660027]])

In [ ]:
# Above, we have created a 10x10 array M of normally distributed random values
# with mean 0 and standard deviation 1
M.shape

(10, 10)

In [ ]:
# Print the mean, standard devietion of all numbers in M
print(f"Mean: {M.mean()}")
print(f"Std Dev: {M.std()}")

Mean: -0.10748955251241046
Std Dev: 0.9820069485142779


In [ ]:
# Print the maximumn, 3rd quartile, median, 1st quartile, and minimum in M
stats = np.percentile(M, [100,75,50,25,0])
max, q3, med, q1, min = stats
print(f"Max: {max}")
print(f"3rd Quartile: {q3}")
print(f"Median: {med}")
print(f"1st Quartile: {q1}")
print(f"Min: {min}")

Max: 1.8545074764442526
3rd Quartile: 0.5334827546958363
Median: -0.07600561088375829
1st Quartile: -0.772777321340235
Min: -2.338781766119939
